//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLySanBongMini.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuanLySanBongMini.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1_15479_soccer_ball_clip_art_soccer_balls_coloring_pages_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("1-15479_soccer-ball-clip-art-soccer-balls-coloring-pages-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1_15479_soccer_ball_clip_art_soccer_balls_coloring_pages_removebg_preview1 {
            get {
                object obj = ResourceManager.GetObject("1-15479_soccer-ball-clip-art-soccer-balls-coloring-pages-removebg-preview1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1601833 {
            get {
                object obj = ResourceManager.GetObject("1601833", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4595_jpg_wh860 {
            get {
                object obj = ResourceManager.GetObject("4595.jpg_wh860", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _6954027 {
            get {
                object obj = ResourceManager.GetObject("6954027", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _71iaJi9LcL_SX425__removebg_preview {
            get {
                object obj = ResourceManager.GetObject("71iaJi9LcL_SX425_-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add {
            get {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add2 {
            get {
                object obj = ResourceManager.GetObject("add2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap addpink_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("addpink-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap backdrop_phong_nen_su_kien_giai_bong_da_dep_file_psd_2051 {
            get {
                object obj = ResourceManager.GetObject("backdrop-phong-nen-su-kien-giai-bong-da-dep-file-psd-2051", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap boscheduler_32x32 {
            get {
                object obj = ResourceManager.GetObject("boscheduler_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btuufon112 {
            get {
                object obj = ResourceManager.GetObject("btuufon112", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap butbut {
            get {
                object obj = ResourceManager.GetObject("butbut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap clean_icon_cleaner_icon_hacker_icon_vQ1cP2c8_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("clean-icon-cleaner-icon-hacker-icon-vQ1cP2c8-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("delete-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ezgif_com_gif_maker_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("ezgif.com-gif-maker-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icloud_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("icloud-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icloud_removebg_preview1 {
            get {
                object obj = ResourceManager.GetObject("icloud-removebg-preview1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_two_settings_cogwheels_icon_cog_icon_png_favpng_updnr1Z5wMVYm37mfx2EGxAdE_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("icon-two-settings-cogwheels-icon-cog-icon-png-favpng-updnr1Z5wMVYm37mfx2EGxAdE-re" +
                        "movebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("images-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_manchester_united_f_c_liverpool_f_c_football_man_attraktive_inspiration_manchester_united_wandtatto_5bf378129f3475_0136628415426826426521_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("kisspng-manchester-united-f-c-liverpool-f-c-football-man-attraktive-inspiration-m" +
                        "anchester-united-wandtatto-5bf378129f3475.0136628415426826426521-removebg-previe" +
                        "w", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lich_thi_dau_bong_da_hom_nay_ngay12_41523479911 {
            get {
                object obj = ResourceManager.GetObject("lich-thi-dau-bong-da-hom-nay-ngay12-41523479911", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NhanVien1 {
            get {
                object obj = ResourceManager.GetObject("NhanVien1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_football_shading_poster_background_vector_material_image_127994 {
            get {
                object obj = ResourceManager.GetObject("pngtree-football-shading-poster-background-vector-material-image_127994", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_football_shading_poster_background_vector_material_image_127994__1___1_ {
            get {
                object obj = ResourceManager.GetObject("pngtree-football-shading-poster-background-vector-material-image_127994 (1) (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap repair_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("repair-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rsz_1_15479_soccer_ball_clip_art_soccer_balls_coloring_pages_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("rsz_1-15479_soccer-ball-clip-art-soccer-balls-coloring-pages-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rsz_addpink_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("rsz_addpink-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rsz_depositphotos_80362150_stock_illustration_money_exchange_icon_from_business_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("rsz_depositphotos_80362150-stock-illustration-money-exchange-icon-from-business-r" +
                        "emovebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rsz_depositphotos_80362150_stock_illustration_money_exchange_icon_from_business_removebg_preview1 {
            get {
                object obj = ResourceManager.GetObject("rsz_depositphotos_80362150-stock-illustration-money-exchange-icon-from-business-r" +
                        "emovebg-preview1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rsz_depositphotos_96581954_stock_illustration_home_circled_icon_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("rsz_depositphotos_96581954-stock-illustration-home-circled-icon-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rsz_kissclipart_search_magnifiers_icon_magnifier_icon_icon_ada5d4bb918dc257_removebg_preview_1 {
            get {
                object obj = ResourceManager.GetObject("rsz_kissclipart-search-magnifiers-icon-magnifier-icon-icon-ada5d4bb918dc257-remov" +
                        "ebg-preview_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rsz_repair_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("rsz_repair-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rsz_transparent_supplier_icon_business_management_icon_inventory_i_5ed798c7e7fca92773728015911876559502_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("rsz_transparent-supplier-icon-business-management-icon-inventory-i-5ed798c7e7fca9" +
                        "2773728015911876559502-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rsz_transparent_supplier_icon_business_management_icon_inventory_i_5ed798c7e7fca92773728015911876559502_removebg_preview1 {
            get {
                object obj = ResourceManager.GetObject("rsz_transparent-supplier-icon-business-management-icon-inventory-i-5ed798c7e7fca9" +
                        "2773728015911876559502-removebg-preview1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap savepink_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("savepink-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap savepink_removebg_preview1 {
            get {
                object obj = ResourceManager.GetObject("savepink-removebg-preview1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap transparent_online_payment_icon_smartphone_icon_payment_icon_5e24073cc2d615_5165774315794194527981_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("transparent-online-payment-icon-smartphone-icon-payment-icon-5e24073cc2d615.51657" +
                        "74315794194527981-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap z2508984184183_1c07aa7b3ef59c19a5100f68077ebc98_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("z2508984184183_1c07aa7b3ef59c19a5100f68077ebc98-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap z2525335187690_01de74b6b6234fce8c62460120cb2841_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("z2525335187690_01de74b6b6234fce8c62460120cb2841-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap z2527808536980_0131e36eb61b5df6cc67674defda4f9b {
            get {
                object obj = ResourceManager.GetObject("z2527808536980_0131e36eb61b5df6cc67674defda4f9b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap z2527813046685_6f539f57a18e943fbedd85a7483a225d {
            get {
                object obj = ResourceManager.GetObject("z2527813046685_6f539f57a18e943fbedd85a7483a225d", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap z2527813051251_34abbf4f15e5e073850e1b80a834fb71 {
            get {
                object obj = ResourceManager.GetObject("z2527813051251_34abbf4f15e5e073850e1b80a834fb71", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
